create sequence hibernate_sequence start with 1 increment by 1;
create table genre (id bigint not null, name varchar(255), primary key (id));
create table genre_movies (genre_id bigint not null, movies_id bigint not null);
create table movie (id bigint not null, title varchar(255), year_of_release integer not null, director_id bigint not null, genre_id bigint, primary key (id));
create table person (id bigint not null, name varchar(255), primary key (id));
create table person_acting_in (actors_id bigint not null, acting_in_id bigint not null);
create table person_director_for (person_id bigint not null, director_for_id bigint not null);
create table review (id bigint not null, created_at date not null, review_text varchar(255), stars integer not null check (stars<=5 AND stars>=1), author_username varchar(255) not null, movie_id bigint not null, primary key (id));
create table user_roles (user_username varchar(255) not null, roles varchar(255));
create table users (username varchar(64) not null, email varchar(255), enabled boolean not null, password varchar(255), primary key (username));
alter table genre_movies add constraint UK_8uvja3h3s2rpg2dt1eqkkj1ky unique (movies_id);
alter table person_director_for add constraint UK_6utvgryit209l6dbvpg8216ci unique (director_for_id);
alter table genre_movies add constraint FKtgatsvi7lb98phh9ft1gogkep foreign key (movies_id) references movie;
alter table genre_movies add constraint FKna0q0v9ce4wywop8o440cv70p foreign key (genre_id) references genre;
alter table movie add constraint FKjk1pk1pnomf5tqi4vodeboo6e foreign key (director_id) references person;
alter table movie add constraint FK2ggat6246891h4goynp4h9lk5 foreign key (genre_id) references genre;
alter table person_acting_in add constraint FKs0snavgwsos5t5wdxyxnb2t6f foreign key (acting_in_id) references movie;
alter table person_acting_in add constraint FKf7ohlbwp5fdsj1bblrjfxl3n6 foreign key (actors_id) references person;
alter table person_director_for add constraint FKsamt3nqukuf43oj88uy5k7wi foreign key (director_for_id) references movie;
alter table person_director_for add constraint FKl3ok49lko4a8f3w1s0oly4p8i foreign key (person_id) references person;
alter table review add constraint FK3brgki1vro5ipydmeqxyr9m1m foreign key (author_username) references users on delete cascade;
alter table review add constraint FK8378dhlpvq0e9tnkn9mx0r64i foreign key (movie_id) references movie;
alter table user_roles add constraint FKs9rxtuttxq2ln7mtp37s4clce foreign key (user_username) references users;