create sequence hibernate_sequence start with 1 increment by 1;
create table genre (id bigint not null, name varchar(20), primary key (id));
create table movie (id bigint not null, description varchar(300), title varchar(50), year_of_release integer not null, director_id bigint not null, primary key (id));
create table movie_actors (acting_in_id bigint not null, actors_id bigint not null);
create table movie_genres (movies_id bigint not null, genres_id bigint not null);
create table person (id bigint not null, name varchar(64), primary key (id));
create table person_director_for (person_id bigint not null, director_for_id bigint not null);
create table review (id bigint not null, created_at date not null, review_text varchar(300), stars integer not null check (stars<=5 AND stars>=1), author_username varchar(255) not null, movie_id bigint not null, primary key (id));
create table user_roles (user_username varchar(255) not null, roles varchar(255));
create table users (username varchar(64) not null, email varchar(255), enabled boolean not null, password varchar(255), primary key (username));
alter table person_director_for add constraint UK_6utvgryit209l6dbvpg8216ci unique (director_for_id);
alter table movie add constraint FKjk1pk1pnomf5tqi4vodeboo6e foreign key (director_id) references person;
alter table movie_actors add constraint FKd1efjfqucfn5k48krp4se9pjd foreign key (actors_id) references person;
alter table movie_actors add constraint FK4v873xova9gpbfvl8lc2h2vqf foreign key (acting_in_id) references movie;
alter table movie_genres add constraint FKi8gl10taq0yvv0aqnuxeal5x0 foreign key (genres_id) references genre;
alter table movie_genres add constraint FKbipbyltnp854o8vbu09lvh6ak foreign key (movies_id) references movie;
alter table person_director_for add constraint FKsamt3nqukuf43oj88uy5k7wi foreign key (director_for_id) references movie;
alter table person_director_for add constraint FKl3ok49lko4a8f3w1s0oly4p8i foreign key (person_id) references person;
alter table review add constraint FK3brgki1vro5ipydmeqxyr9m1m foreign key (author_username) references users on delete cascade;
alter table review add constraint FK8378dhlpvq0e9tnkn9mx0r64i foreign key (movie_id) references movie;
alter table user_roles add constraint FKs9rxtuttxq2ln7mtp37s4clce foreign key (user_username) references users;